# Generated by Django 5.2.13 on 2026-04-26 14:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Companion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dna_seed', models.PositiveBigIntegerField(editable=False, unique=True)),
                ('unique_code', models.CharField(editable=False, max_length=12, unique=True)),
                ('species', models.CharField(default='companion-alpha', editable=False, max_length=24)),
                ('parent_username_at_birth', models.CharField(editable=False, max_length=150)),
                ('birth_at', models.DateTimeField(auto_now_add=True)),
                ('founder_number', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_in_coma', models.BooleanField(default=False)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='companion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BehaviorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=40)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('companion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='companion.companion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanionMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_type', models.CharField(choices=[('owner_name', 'Owner name'), ('preference', 'Preference'), ('schedule', 'Schedule'), ('event', 'Event'), ('nickname', 'Nickname')], max_length=20)),
                ('key', models.CharField(max_length=80)),
                ('value', models.TextField()),
                ('confidence', models.FloatField(default=0.5)),
                ('learned_at', models.DateTimeField(auto_now_add=True)),
                ('last_referenced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('companion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='companion.companion')),
            ],
            options={
                'ordering': ['-learned_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanionTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait', models.CharField(choices=[('affection', 'affection'), ('discipline', 'discipline'), ('curiosity', 'curiosity'), ('confidence', 'confidence'), ('playfulness', 'playfulness')], max_length=20)),
                ('value', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('companion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='companion.companion')),
            ],
        ),
        migrations.AddIndex(
            model_name='companion',
            index=models.Index(fields=['founder_number'], name='companion_c_founder_4f6b3b_idx'),
        ),
        migrations.AddIndex(
            model_name='companion',
            index=models.Index(fields=['birth_at'], name='companion_c_birth_a_304dad_idx'),
        ),
        migrations.AddIndex(
            model_name='behaviorevent',
            index=models.Index(fields=['companion', '-created_at'], name='companion_b_compani_3839a9_idx'),
        ),
        migrations.AddIndex(
            model_name='companionmemory',
            index=models.Index(fields=['companion', 'fact_type'], name='companion_c_compani_40d5f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companionmemory',
            unique_together={('companion', 'fact_type', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='companiontrait',
            unique_together={('companion', 'trait')},
        ),
    ]
