# Generated by Django 5.2.13 on 2026-04-26 14:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companion',
            name='archetype_locked',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='companion',
            name='archetype_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companion',
            name='coma_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companion',
            name='disease',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='companion',
            name='disease_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companion',
            name='energy',
            field=models.PositiveSmallIntegerField(default=80),
        ),
        migrations.AddField(
            model_name='companion',
            name='happiness',
            field=models.PositiveSmallIntegerField(default=80),
        ),
        migrations.AddField(
            model_name='companion',
            name='hunger',
            field=models.PositiveSmallIntegerField(default=80),
        ),
        migrations.AddField(
            model_name='companion',
            name='hygiene',
            field=models.PositiveSmallIntegerField(default=85),
        ),
        migrations.AddField(
            model_name='companion',
            name='immunity',
            field=models.PositiveSmallIntegerField(default=70),
        ),
        migrations.AddField(
            model_name='companion',
            name='last_decay_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='companion',
            name='last_interaction_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
