# Generated by Django 5.2.13 on 2026-04-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companion', '0002_companion_archetype_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companion',
            name='pledge_signature',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='companion',
            name='pledge_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
