# Generated by Django 5.2.13 on 2026-04-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companion', '0003_companion_pledge_signature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('severity', models.PositiveSmallIntegerField(default=1)),
                ('duration_hours', models.PositiveIntegerField(default=24)),
                ('symptoms', models.JSONField(default=list)),
                ('cure_items', models.JSONField(default=list)),
                ('weight', models.FloatField(default=1.0)),
            ],
        ),
    ]
