# Generated by Django 5.2.13 on 2026-04-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companion', '0004_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='companion',
            name='bladder',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='companion',
            name='is_sleeping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companion',
            name='sleep_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
